### ISSUE TITLE
Refactor MapObject / MapObjectCreator name convention

### ISSUE THREAD

**Issue by emilbartholdy** [NoticeMeDan/map#15]
Consider using a Entity structure/folder (information containers with only getters and setters) to contain entities of objects, so they doesn't get confused with functionality objects

**Comment by MrMatten** [comment]
@EliasJorgensen  DTO'er eller entiteter?

**Comment by MrMatten** [comment]
@Silind andre forslag velkomne

**Comment by EliasJorgensen** [comment]
@MrMatten Kommer an på hvad de skal bruges til. DTO = Domain Transfer Object

**Comment by MrMatten** [comment]
Altså jeg er ikke 100p inde i terminologien, men jeg kunne godt tænke mig det samme som vi havde med entiterne i cinema, altså "pure" objekter kun med felter og getter og setter metoder. Hvis det giver mening i MVVM

**Comment by EliasJorgensen** [comment]
Der var det entiteter, men det var fordi at vi brugte en DB.
I databaser er hver række en entitet.
Men ja, kan godt se hvor du vil hen - Data klasser.
Hvis @emilbartholdy kan komme med et eksempel på hvad de skal bruges til, så kan jeg lige forhøre the grand wizard om hvad den korrekte betegnelse er.

**Comment by MrMatten** [comment]
Det var mig der skrev det, fra hans computer, det er OSMType (nuværende MapObject), så er det Forest klassen og hvis der er andre

**Comment by emilbartholdy** [comment]
Vi har ændret MapObject → OSM element
