### ISSUE TITLE
Coastlines not stiched properly

### ISSUE THREAD

**Issue by SimonHoiberg** [NoticeMeDan/map#17]
Algorithms that iterates through coastlines and merges them together doesn't work.
It stiches the coastlines and returns associated CoastlineObjects which are drawn, but not correctly.

- [x] Create test-shapes to investigate further
- [x] Create unit test to validate correction

**Comment by emilbartholdy** [comment]
Kan denne issue lukkes, nu da vi benytter Martins kode?
