### ISSUE TITLE
Clean-up code

### ISSUE THREAD

**Issue by emilbartholdy** [NoticeMeDan/map#38]
- [x] XMLParser
- [x] Remove deprecated code (e.g. observer)
- [x] Clean up canvas code

- [x] Make UI code modular / refactor it to behave in a logical consistent way.

**Comment by emilbartholdy** [comment]
- [ ] XMLParser (Coastline stitching, address extraction)
- [ ] Remove deprecated code (e.g. observer)
- [ ] Clean up canvas code

**Comment by EliasJorgensen** [comment]
Har fjernet Adresse extraction fra dette issue, da det ikke tæller som Cleanup.
