### ISSUE TITLE
Save and load to binary format

### ISSUE THREAD

**Issue by SimonHoiberg** [NoticeMeDan/map#45]
## Allow the user to save and load the current model to and from a binary format which must be documented in the report.

- [x] Give KDTreeNodes unique binary id's.
- [x] Convert KDTree-leafs (OSMelements arrays) to binary files.
- [x] Convert KDTree-leafs (OSMelements arrays) from binary files back to normal arrays.
- [x] Store binary files in 'hidden folder' 
- [x] Convert OSMElements to binary code when KDTree processing is finished.
- [x] Read OSMElements from binary code when using rangeSearch.
- [x] Examine if this operation is fast enough to work in practice (should be!)
- [x] Convert KDTree(s) to binary code asynchronously after creation
- [x] Make program load KDTrees from binary code (not the OSMElements at the leaves!)

**Comment by EliasJorgensen** [comment]
Done diddly done.
Bliver gjort lidt mere simpelt end håbet, grundet tidspres.
