### ISSUE TITLE
Range Search

### ISSUE THREAD

**Issue by emilbartholdy** [NoticeMeDan/map#64]
Det virker som om der er sket en fejl i Eliases refactorering af koden. Range search returnerer meget mere sporadiske resultater.

Jeg mistænker at det kan være sket i omnavngivningen af OSMMaterialElement til OsmElement.

Dette har vi prøvet indtilvidere:

- Kalde repaint() ved mouseDrag.
- Lave større søgeareal (HOTFIX) → virker til dels med meget dårligere performance.
- Printe avgPoint ud fra XML parser før og efter refaktorering (tal er ens). Se udsnit.

Jeg har kørt kdtree tests på følgende commits:
23a299ea5b06f8b202c34fdee1b7b8b10aa792ba (KDTree tests fail! RangeSearch tests fail!)
64335f7a3913dfbee8625de3a0809e6c149ab21f (Check)
01d26424580993c2d13afb76509084eaa26cb595 (Check)
033a717f5123af45a0b69eece368003ed87f1d48 (Check)

**Comment by emilbartholdy** [comment]
Buggen blev forbedret ved at fjerne Eliases builder, men der er stadigvæk fejl: 
Se fx følgende:

<img width="1212" alt="screen shot 2018-04-23 at 12 56 14" src="https://user-images.githubusercontent.com/34028316/39122616-c298ebb0-46f5-11e8-8922-19f2c1686330.png">
<img width="1212" alt="screen shot 2018-04-23 at 12 54 28" src="https://user-images.githubusercontent.com/34028316/39122617-c2b68a12-46f5-11e8-83dc-096c7ffd2a00.png">

Læg mærke til den orange vej. De commits der sammenlignes er 
64335f7 (virker)
b45fd0cb8a9af118a903ec4005df5d489b7ef3be (virker ikke)

**Comment by EliasJorgensen** [comment]
Jamen det var godt nok et fint switch statement der var blevet lavet.
:rocket:
