### ISSUE TITLE
Objects are painted randomly in paint()

### ISSUE THREAD

**Issue by emilbartholdy** [NoticeMeDan/map#70]
Before objects were painted in a certain order e.g. parks → lakes → roads → ternary road → secondary road → and so on.

Now they are painted randomly which results in situations such as these:

<img width="589" alt="screen shot 2018-04-26 at 10 00 27" src="https://user-images.githubusercontent.com/34028316/39293260-bb92bb44-4938-11e8-86bf-9e510183a5b8.png">

How it should look:

<img width="1035" alt="screen shot 2018-04-26 at 10 00 50" src="https://user-images.githubusercontent.com/34028316/39293272-c0e73872-4938-11e8-9d5f-8f630bc9a0ce.png">

Suggested solution: Sort objects into the old enummap again?

**Comment by IMarnild** [comment]
- [x] fixed

**Comment by MrMatten** [comment]
Hvor ser det godt ud!
